import turtle
t = turtle.Turtle()
turtle.Screen().bgcolor('black')
t.speed(10)
t.pensize(10)
t.color('cyan')
t.circle(100)
t.color('orange')
t.penup()
t.setposition(-240,0)
t.pendown()
t.circle(100)
t.color('red')
t.penup()
t.setposition(120,120)
t.pendown()
t.circle(100)
t.color('yellow')
t.penup()
t.setposition(-120,120)
t.pendown()
t.circle(100)
t.color('violet')
t.penup()
t.setposition(-360,120)
t.pendown()
t.circle(100)
